### ISSUE TITLE
stdlib.file: --mode argument checked strict

### ISSUE THREAD

**Issue by jlaynereallyfast** [jtopjian/waffles#107]
Hello,

I'm starting to use waffles to set up a personal server.  Thank you for sharing it, I really enjoy its simplicity.

The issue I'm having is that file and directory resources are always considered to be out-of-date when the permissions are prepended a zero (as usual in C to denote octals, and accepted by `chmod`).

For example:

``` .bash
stdlib.file /tmp/abc --mode 0755
```

The issue is caused by `stat` which returns unprefixed octals, and string instead of arithmetic comparison.  The following patch seems to help:

``` .patch
diff --git i/lib/stdlib/resources/directory.sh w/lib/stdlib/resources/directory.sh
index 7d10a51..8f1fb91 100644
--- i/lib/stdlib/resources/directory.sh
+++ w/lib/stdlib/resources/directory.sh
@@ -68,7 +68,7 @@ function stdlib.directory.read {
   stdlib.split "$_stats" ':'
   _owner="${__split[0]}"
   _group="${__split[1]}"
-  _mode="${__split[2]}"
+  _mode="0${__split[2]}"
   _type="${__split[3]}"

   if [[ $_type != "directory" ]]; then
@@ -87,7 +87,7 @@ function stdlib.directory.read {
     return
   fi

-  if [[ ${options[mode]} != $_mode ]]; then
+  if [[ ${options[mode]} -ne $_mode ]]; then
     stdlib_current_state="update"
     return
   fi
diff --git i/lib/stdlib/resources/file.sh w/lib/stdlib/resources/file.sh
index 22145f6..3d40223 100644
--- i/lib/stdlib/resources/file.sh
+++ w/lib/stdlib/resources/file.sh
@@ -74,7 +74,7 @@ function stdlib.file.read {
   stdlib.split "$_stats" ':'
   _owner="${__split[0]}"
   _group="${__split[1]}"
-  _mode="${__split[2]}"
+  _mode="0${__split[2]}"
   _type="${__split[3]}"
   _md5=$(md5sum "${options[name]}" | cut -d' ' -f1)

@@ -102,7 +102,7 @@ function stdlib.file.read {
     return
   fi

-  if [[ ${options[mode]} != $_mode ]]; then
+  if [[ ${options[mode]} -ne $_mode ]]; then
     stdlib_current_state="update"
     return
   fi
```

**Comment by jtopjian** [comment]
This is something I also run into and have been putting off a proper fix. Now that there's an official "issue", I have to fix it :wink: 

I think `printf` can help here:

``` shell
$ printf %04d 755
0755
$ printf %04d 2755
2755
```

I'll look at incorporating this into `stdlib.file` and `stdlib.directory`. :smile:

**Comment by jtopjian** [comment]
Let me know if you see any problems with #109. It should account for both zero-padded and non-zero-padded file permissions.

**Comment by jlaynereallyfast** [comment]
Another option would be:

``` .bash
to_octal() {
  printf "%o" "0$1";
}
to_octal 0755
755
to_octal 755
755
to_octal 000755
755
```

though I can't think of a failure case for your implementation.

Thank you!

**Comment by jtopjian** [comment]
Ah - that's really interesting. Normalizing the setting in the opposite way :smile: 

I think I've been able to get away with this without using `printf`. I'll merge for now and revisit if there's something which was missed.

Thank you for your help and reporting this!
