### ISSUE TITLE
Ability to create symbolic links

### ISSUE THREAD

**Issue by jlaynereallyfast** [jtopjian/waffles#108]
I would like to create/manage a symbolic link.

An option could be to allow a special state in the `stdlib.file`, as in Puppet:

``` .bash
stdlib.file --name /tmp/aaa --state link --target /tmp/bbb
```

though a special resource `stdlib.link` might be simpler.  What do you think?

**Comment by jtopjian** [comment]
Yup, this is another one I've just been too lazy to fix.

I agree about `--state link`. This would match Puppet's `file` resource behavior. I'll look into implementing it. If it becomes too unwieldy, maybe `stdlib.link` would be simpler, as you said.

**Comment by jlaynereallyfast** [comment]
Personally, I think the stdlib.link fits more with the current approach, and avoids overloading the `--state`.  Chef seems to use a separate link resource https://docs.chef.io/resource_link.html...

**Comment by jtopjian** [comment]
Added in #131 :smile:
