### ISSUE TITLE
Get name of profile using a resource

### ISSUE THREAD

**Issue by jlaynereallyfast** [jtopjian/waffles#113]
In some situations, it might be useful to have access to the using profile's name from within a resource implementation.  For example, one might combine the resource name with the using profile to set the default path for some file in the profile's `files`:

``` .bash
# This is the wordpress profile.  We have a backported .deb we want
# to install via a dpkg.deb resource.

dpkg.deb --name waffles --version 1.0 --deb "${WAFFLES_SITE_DIR}/profiles/wordpress/files/wordpress_1.0_amd64.deb";

# It would be easier this way, where the resource derives the package path from the profile, the package name and version.
dpkg.deb --name waffles --version 1.0;
```

The example might be not too clear; please, ask for clarification if needed.

Puppet offers that as the `$caller_module_name` variable.  It looks to me that `caller` (http://wiki.bash-hackers.org/commands/builtin/caller) could be used to retrieve the name.

**Comment by jtopjian** [comment]
I think I understand.

I just merged a [patch](https://github.com/jtopjian/waffles/commit/a589865e2587c5ac0c0cf36cc11856eb35ee45bb) that exposes `$profile_path`. 

I could modify that area a bit more so that `$profile` is available rather than `$_profile` (I'm using underscores to denote variables that shouldn't be used outside of the current context.

_In theory_, `$profile` and `$profile_path` will be available from within the resource. I haven't tested it out, though.

**Comment by jlaynereallyfast** [comment]
That's great!

I'm going to try it and will report back.

Exposing a couple of new functions might make sense:
- `stdlib.current_profile` returns the profile name.
- `stdlib.profile_path` accepts a profile name and returns its path.  If no name is provided it returns the path of current profile.  This would be quite useful for constructing file names as well:
  
  ``` .bash
  --source "${WAFFLES_SITE_DIR}/profiles/wordpress/files/wordpress_1.0_amd64.deb"
  --source "$(stdlib.profile_path)/files/wordpress_1.0_amd64.deb"
  ```
  
  Though a specialiced function would be nicer:
  
  ``` .bash
  --source "$(stdlib.files_path "wordpress_1.0_amd64.deb")"
  ```

Now I'm going to test it.

**Comment by jtopjian** [comment]
Very interesting ideas! I also like the clever way of self-configuring resources by auto-discovering information about their calling profiles.

Let me think on those functions. I like their general idea.

**Comment by jlaynereallyfast** [comment]
Hello, just wanted to report that $profile_path works.  But when one includes a profile from within another, the latter's path is set.  For example:

``` .bash
# This is the wordpress profile.  We need the dpkg profile in order to have access to the dpkg.deb resource.
echo profile_path=$profile_path; # returns .../profiles/wordpress
stdlib.profile dpkg
echo profile_path=$profile_path; # returns .../profiles/dpkg
```

Would that be the right way of expressing dependency on resources from another package?  I get a few "Duplicate resource detected" warnings.  It might make sense to have a function such as `stdlib.requires` that asserts that the given profile has been `stdlib.profile` included before.

(Edited.)

**Comment by jtopjian** [comment]
Profiles weren't designed to be nested to avoid messy situations like that. I think if nested profiles were supported, Waffles would have to change from a fairly simple way of organizing scripts to a graph dependency system, which I think would be a nightmare to handle in Bash. :smile: 

The lack of support for nested profiles no doubt causes explicitly long roles, but I think the tradeoff is worthwhile.

**Comment by jtopjian** [comment]
I've opened #116 which exposes `$profile_name` and `$profile_files`. So now the following should be easily accessible:
- `$profile_name`
- `$profile_path`
- `$profile_files`

I thought about creating the ability to look up other profile information, but I think I will hold off on that for now. I'd like to keep profiles as independent as possible and not have any way for them to communicate with each other. Let me know if you have a use-case in mind where a profile should be able to use another profile's scripts or files.

**Comment by jlaynereallyfast** [comment]
This is wonderful!  Thank you.
Probably worth it to change the few places in the documentation where `$WAFFLES_SITE_DIR` is used.

**Comment by jtopjian** [comment]
Good call. I'll roll a doc update into #116.
