### ISSUE TITLE
stdlib.apt_source does not support Flat Repository Format

### ISSUE THREAD

**Issue by jlaynereallyfast** [jtopjian/waffles#114]
Currently, the --components option must be non-empty, as it is a `__required__` option.  This prevents specifying componentless sources such as the following (please, see https://wiki.debian.org/RepositoryFormat#Flat_Repository_Format):

```
   deb uri file:///some/directory/
```

The `--components` option should probably be made optional.

**Comment by jtopjian** [comment]
Let me know if #115 helps. It's just a quick change from `__required__` to optional.

**Comment by jlaynereallyfast** [comment]
Yes, that's all needed.  Thank you!
