### ISSUE TITLE
os.symlink options are ambiguous

### ISSUE THREAD

**Issue by jlaynereallyfast** [jtopjian/waffles#158]
The meaning of `--source` and `--destination` seems non-intuitive.  In my mind, source ~= origin and destination ~= target, but the resource is implemented in the opposite manner (`--destination` is the link file and `--source` is the target).  Of course, this is all very subjective.

Would it be possible/make sense to switch them to `--name` for the link file, and `--target` (or `--source`, for consistency with `os.file`)?

Apologies for bringing this so late.

**Comment by jtopjian** [comment]
Good point. I've always viewed symlinks in the opposite direction than what is reported, and this might have leaked through.

`--name` and `--target` sound like good options to me.

**Comment by jtopjian** [comment]
This is fixed in both master and the 0.22 branch.
