### ISSUE TITLE
Introduce resource dependencies

### ISSUE THREAD

**Issue by gbraekmans** [jtopjian/waffles#174]
On a RedHat system apt.pkg, waffles fails with:

```
.../waffles/resources/apt_pkg.sh: line 57: apt-cache: command not found
apt.pkg error: No such package: sudo
```

I would expect something like

```
apt.pkg error: resource dependency not installed: apt-cache
```

**Comment by jtopjian** [comment]
This is a really good catch. I've opened #176 that will check for dependencies on all resources. The idea is to list the required commands early in the resource and error early and cleanly if one isn't found.

I still need to run the changes through Test Kitchen to catch any typos or errors.
