### ISSUE TITLE
Possible removal of RabbitMQ resources

### ISSUE THREAD

**Issue by jtopjian** [jtopjian/waffles#178]
[Rabbit Hole](https://github.com/michaelklishin/rabbit-hole) is a complete Go library for managing RabbitMQ resources. I'm going to look into making them Terraform resources and then possibly remove the existing RabbitMQ Waffles resources.

**Comment by gbraekmans** [comment]
Again why? It seems to me that having extra resources is a good thing.

**Comment by jtopjian** [comment]
Everything in #177 is applicable here, too. One extra thing specific to RabbitMQ is that a [previous version](https://github.com/wffls/waffles/tree/0.22/lib/resources) of Waffles had more RabbitMQ resources than there are now. The caveat was that they required Augeas. 

A few weeks ago I stripped down Waffles and Augeas was one of the things that got cut. I haven't found a good reason to bring it back yet. 

If more RabbitMQ resources would be added to Waffles, I'd be more inclined to use the RabbitMQ management API rather than interacting with RabbitMQ's wacky config file syntax.

**Comment by jtopjian** [comment]
These are going to stay, too, though I might try to alter them a bit to use the Management REST API. I've just finished a bunch of work with Terraform and RabbitHole and it was a breeze to use.
