### ISSUE TITLE
Make waffles compatible with the errexit and nounset option

### ISSUE THREAD

**Issue by gbraekmans** [jtopjian/waffles#185]
This is a debugging effort for the waffles code.
- "errexit" is equivalent to set -e and makes bash exit on any unexpected error.
- "nounset" is equivalent to set -u and makes bash exit on usage of an unset variable.

These settings would make it harder for bugs to sneak into the scripts. The actual setting may be left to the user.

I guess the nounset option doesn't require any work, and if it does it will be mostly bugs. The errexit requires more work, but [this workaround](http://stackoverflow.com/a/28899718) seems very manageable.

**Comment by gbraekmans** [comment]
@multicast I've taken a quick look at your fork and it seems you working on this? Even before I've managed to make this an issue. :smile:

**Comment by jtopjian** [comment]
I've just dug into this as well as looked at @multicast's patches. Thank you both for raising this.

`-u` sounds like a good idea to have set within Waffles, regardless of if the user turns it on in their Waffles script.

With regard to `-e`, it looks like @multicast's patches are making it so the resource _doesn't_ exit early if the command fails. I agree with this. If the resource ultimately returns a code >0, then `-e` should be triggered and the script should exit.

**Comment by jtopjian** [comment]
Also, @multicast, please feel free to submit PRs for your work. Or I can just cherry-pick them so your credit is in the git history and CHANGELOG file :smile:

**Comment by jtopjian** [comment]
@multicast: ping 

I'm going to have some time to start reviewing this more in depth. I really like the updates you've made to your fork including the style of how you're handling `set -e`. 

I was wondering if you had plans to open a PR with your fixes? If not, I'd like to manually merge them into Waffles. Just wanted to get your feelings on that as I'd feel a bit awkward doing it without your consent. :)

**Comment by jtopjian** [comment]
I have a WIP pull request in progress at #198.

**Comment by multicast** [comment]
pardon, got busy last month and although I made some resources set -e compatible, I haven't made it to PR yet. I review my changes and squash similar commits this or netxt week.

**Comment by jtopjian** [comment]
@multicast no worries at all. #198 has all of your changes to date :)

**Comment by jtopjian** [comment]
I finally had time to revisit #198 and merged it. I don't think this is 100% complete, but there has been a lot of work done toward it. I think from here, pointing out individual areas where `set -e` and `set -u` aren't working is the best approach.
