### ISSUE TITLE
New Resource: yum

### ISSUE THREAD

**Issue by jtopjian** [jtopjian/waffles#5]
A yum resource for RPM-based distributions would be nice.

**Comment by jtopjian** [comment]
Removing "help wanted" tag, but help is always wanted -- that should be implicit with open source projects. :)

**Comment by gbraekmans** [comment]
I've got basic dnf suport  (dnf.pkg) in the fedora branch of my clone. Working on bringing support for COPR (fedora's PPA) and other repo's.

How would I implement support for installing individual RPM's?

**Comment by jtopjian** [comment]
Awesome!

I've used Puppet, Chef, etc as the basis for starting new resources. The underlying shell commands `apt.pkg` resource, for example, started from [here](https://github.com/puppetlabs/puppet/blob/98d22be27447bcb34c33aa4a44610ab8768390f5/lib/puppet/provider/package/apt.rb). Maybe the [rpm](https://github.com/puppetlabs/puppet/blob/98d22be27447bcb34c33aa4a44610ab8768390f5/lib/puppet/provider/package/rpm.rb) provider would be helpful?

**Comment by jtopjian** [comment]
Implemented in #175
